{
  generate=[
    java="8"
    names="long"
//    psi-classes-map="yes"
  ]

  parserClass="dev.blachut.svelte.lang.parsing.top.SvelteParser"

  extends="dev.blachut.svelte.lang.psi.SveltePsiElementImpl"

  psiClassPrefix="Svelte"
  psiImplClassSuffix="Impl"
  psiPackage="dev.blachut.svelte.lang.psi"
  psiImplPackage="dev.blachut.svelte.lang.psi.impl"

  elementTypeHolderClass="dev.blachut.svelte.lang.psi.SvelteTypes"
  elementTypeClass="dev.blachut.svelte.lang.psi.SvelteElementType"
  tokenTypeClass="dev.blachut.svelte.lang.psi.SvelteElementType"

  tokens = [
    START_OPENING_MUSTACHE="{#"
    START_INNER_MUSTACHE="{:"
    START_CLOSING_MUSTACHE="{/"
    START_MUSTACHE="{"
    START_MUSTACHE_TEMP="START_MUSTACHE_TEMP"
    END_MUSTACHE="}"
    IF="if"
    EACH="each"
    AS="as"
    COMMA=","
    START_PAREN="("
    END_PAREN=")"
    AWAIT="await"
    THEN="then"
    CATCH="catch"
    ELSE="else"
    HTML_PREFIX="@html"
    DEBUG_PREFIX="@debug"
    HTML_FRAGMENT="<markup>"
    CODE_FRAGMENT="<code>"
    LAZY_IF="LAZY_IF"
    LAZY_ELSE="LAZY_ELSE"
    LAZY_EACH="LAZY_EACH"
    LAZY_AWAIT="LAZY_AWAIT"
    LAZY_THEN="LAZY_THEN"
    LAZY_CATCH="LAZY_CATCH"
    TEMP_PREFIX="TEMP_PREFIX"
    HASH="HASH"
    COLON="COLON"
    SLASH="SLASH"
    AT="AT"
  ]
}

// First rule is always implicitly private
svelteComponent ::= privateScope
scope ::= privateScope

private privateScope ::= HTML_FRAGMENT

