{
  generate=[
    java="8"
    names="long"
//    psi-classes-map="yes"
  ]

  parserClass="dev.blachut.svelte.lang.parsing.top.SvelteParser"

  extends="dev.blachut.svelte.lang.psi.SveltePsiElementImpl"

  psiClassPrefix="Svelte"
  psiImplClassSuffix="Impl"
  psiPackage="dev.blachut.svelte.lang.psi"
  psiImplPackage="dev.blachut.svelte.lang.psi.impl"

  elementTypeHolderClass="dev.blachut.svelte.lang.psi.SvelteTypes"
  elementTypeClass="dev.blachut.svelte.lang.psi.SvelteElementType"
  tokenTypeClass="dev.blachut.svelte.lang.psi.SvelteElementType"

  tokens = [
    START_MUSTACHE="{"
    START_MUSTACHE_TEMP="START_MUSTACHE_TEMP"
    END_MUSTACHE="}"
    HTML_FRAGMENT="<markup>"
    CODE_FRAGMENT="<code>"
    LAZY_IF="LAZY_IF"
    LAZY_ELSE="LAZY_ELSE"
    LAZY_EACH="LAZY_EACH"
    LAZY_AWAIT="LAZY_AWAIT"
    LAZY_THEN="LAZY_THEN"
    LAZY_CATCH="LAZY_CATCH"
    TEMP_PREFIX="TEMP_PREFIX"
    HASH="HASH"
    COLON="COLON"
    SLASH="SLASH"
    AT="AT"
  ]
}

svelteComponent ::= privateScope

private privateScope ::= HTML_FRAGMENT

